"""
Django settings for AVENDRE project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vhu%!qst85rr=s!1=$jpt@ef!fk@sv4^6-6=wc8c2a3yaks1a4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'chat',
    'users',
    'crispy_forms',
    'crispy_bootstrap5'
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AVENDRE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AVENDRE.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

LOGIN_REDIRECT_URL='blog-index'
LOGIN_URL = 'users-login'
STATIC_URL = 'static/'
MEDIA_URL ='/media/'
MEDIA_ROOT = (BASE_DIR /'media')
STATIC_ROOT = (BASE_DIR / 'asset')
#STATICFILES_DIRS=[BASE_DIR/'static']


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CRISPY_TEMPLATE_PACK = 'bootstrap5'



JAZZMIN_UI_TWEAKS={
    "navbar_small_text": False,
    "footer_small_text":False,
    "body_small_text":True,
    "brand_small_text":False,
    "brand_color":"navbar-indigo",
    "accent":"accent-olive",
    "navbar":"navbar-indigo navbar-dark",
    "no_navbar_border":False,
    "navbar_fixed":False,
    "layout_fixed": False,
    "footer_fixed": False,
    "sidebar_fixed":False,
    "sidebar":"sidebar-dark-indigo",
    "sidebar_nav_small_text":False,
    "sidebar_disable_expand":False,
    "sidebar_nav_child_indent":False,
    "sidebar_nav_compact_style":False,
    "sidebar_nav_legacy_style":False,
    "sidebar_nav_flat_style":False,
    "theme":"slate",
    "dark_mode_theme":"slate",
    "button_classes":{
       "primary":"btn-primary",
       "secondary":"btn-secondary",
       "info":"btn-info",
       "warning":"btn-warning",
       "danger":"btn-danger",
       "success":"btn-success", 
    }



}


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
