# Generated by Django 5.0.6 on 2024-11-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_title_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='chambres',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='telephone',
            field=models.IntegerField(default=0),
        ),
    ]
