# Generated by Django 5.0.6 on 2024-11-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_content_post_chambres_post_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='chambres',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
