# Generated by Django 5.0.6 on 2024-11-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_description_post_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(max_length=500),
        ),
    ]
