# Generated by Django 5.0.6 on 2024-11-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_description_alter_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prix_en_fbu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
