# Generated by Django 5.0.6 on 2024-11-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='telephone',
            field=models.IntegerField(max_length=12),
        ),
    ]
